### ISSUE TITLE
Can't Compile the Project: pgesupportprx.h is missing on pge.c:33

### ISSUE THREAD

**Issue by MasterMenSilver** [KapLex/PGE#2]
I am trying to compile the PGE again and i even solved the problem with the wrong freetype path but i just don't have pgesupportprx.h in "Support" folder, i don't know where i would get it, if you can give me it, please, do.
I do really need an already working and compileable project.

**Comment by MasterMenSilver** [comment]
Found solutions, proceeded.

**Comment by Rottenland** [comment]
What were your solutions? I'm currently facing the same problem
